version: '3.8'
services:
  stark-queue:
    image: redis:latest
    container_name: stark-queue
    ports:
      - "6381:6379"
  stark-verifier:
    build:
      context: .
      dockerfile: Dockerfile.stark
    container_name: stark-verifier
    depends_on:
      - stark-queue
    environment:
      - REDIS_HOST=stark-queue
      - REDIS_PORT=6379
    command: ["python", "STARKVerifierWorker.py", "--redis-port", "6379"]
